services:

infrastructure.experiences_repository:
  class: App\Infrastructure\Repository\Resume\ExperiencesRepository

infrastructure.skills_repository:
  class: App\Infrastructure\Repository\Resume\SkillsRepository

infrastructure.presentation_repository:
  class: App\Infrastructure\Repository\Resume\PresentationRepository

